version: '3'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: 'postgres'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ejaw
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-network

  migrate:
    container_name: migrate
    image: 'migrate/migrate'
    command: [
      "-path", "/internal/migrations",
      "-database", "postgres://admin:password@db:5432/ejaw?sslmode=disable",
      "up"
    ]
    volumes:
      - ./internal/migrations:/internal/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge